In [1]:
import pandas as pd
import numpy as np

In [2]:
from pathlib import Path

In [3]:
# Finance
df_finance = pd.read_excel("/Users/CoursM2/Documents/Alberthon/Sujet Alberthon/Finance/AlbertSchool_CACEIS_PL-FTE_22-25_Sent.xlsx")

# Training
df_training = pd.read_excel("/Users/CoursM2/Documents/Alberthon/Sujet Alberthon/Training/Training_Records_Unnamed.xlsx")
df_cold = pd.read_excel("/Users/CoursM2/Documents/Alberthon/Sujet Alberthon/Training/Cold_Review_Unnamed.xlsx")

# Absence
df_abs = pd.read_excel("/Users/CoursM2/Documents/Alberthon/Sujet Alberthon/HR Data/20260121 - Absentéisme_-_détail_affectation_-_Bilan_social 2025.xlsx")

In [4]:
# Vérification rapide des fichiers chargés

print("Finance :", df_finance.shape)
print("Training :", df_training.shape)
print("Cold review :", df_cold.shape)
print("Absence :", df_abs.shape)

display(df_finance.head())
display(df_training.head())
display(df_cold.head())
display(df_abs.head())

Finance : (12, 11)
Training : (14943, 12)
Cold review : (8647, 23)
Absence : (127825, 46)

,Toutes Filiales conso,Réel décembre 2022,Réel décembre 2023,Réel décembre 2024,Réel décembre 2025,Unnamed: 5,o/w Europe,Réel décembre 2022.1,Réel décembre 2023.1,Réel décembre 2024.1,Réel décembre 2025.1
0,Net Commission Income,8.986520e+05,1.039248e+06,1.296794e+06,1.310191e+06,NaN,Net Commission Income,8.986520e+05,1.039441e+06,1.298118e+06,1.310091e+06
1,Net Interest Margin,4.186306e+05,6.944518e+05,8.265549e+05,8.676323e+05,NaN,Net Interest Margin,4.186306e+05,6.942633e+05,8.265514e+05,8.681490e+05
2,Other Income / (expense),-6.731757e+04,-5.636783e+04,-3.991230e+04,-7.781260e+04,NaN,Other Income / (expense),-6.731757e+04,-5.900319e+04,-4.145521e+04,-7.782268e+04
3,Net Banking Income (PNB),1.249965e+06,1.677332e+06,2.083437e+06,2.100011e+06,NaN,Net Banking Income (PNB),1.249965e+06,1.674701e+06,2.083214e+06,2.100417e+06
4,Rémunérations & charges,-3.923482e+05,-5.149449e+05,-6.580353e+05,-6.787855e+05,NaN,Rémunérations & charges,-3.923482e+05,-5.026284e+05,-6.309239e+05,-6.479100e+05

,Employee Code,Entity,Direction,Attended_Courses,Organization,Seesion_Start_Date,Session_End_Date,Session_ID,Status,Total_Training_Hours,Certifications,Year
0,NaN,NaN,NaN,Modèle de données GP4,NEOXAM,15/10/2025,17/10/2025,25-MDG-859-226,Réalisé,21.0,No,2025
1,NaN,CACEIS Bank,NaN,2024 International compliance trainings,IFCAM,29/11/2024,29/11/2024,NaN,Annulée,0.0,No,2024
2,NaN,CACEIS Bank,NaN,7Speaking plateforme licences annuelles,7Speaking,2025-06-01 00:00:00,2025-06-01 00:00:00,24-7PL-451-669,Réalisé,0.5,No,2025
3,NaN,CACEIS Bank,NaN,7Speaking plateforme licences annuelles,7Speaking,15/12/2023,15/12/2023,23-7PL-451-343,Réalisé,0.1,NaN,2023
4,NaN,CACEIS Bank,NaN,Accompagnement à la négociation commerciale,Dale Carnegie,NaN,NaN,NaN,Annulée,14.0,No,2025

,Date,Matricule,Formation,Organization,Session_ID,Date de début de session,Date de fin de session,Lieu de session,Status,Considérez-vous que cette formation vous a permis de prendre confiance en vous :,...,Considérez-vous que cette formation vous a permis de développer de nouvelles compétences :,Autres (à préciser),La formation visait-elle la préparation d’un diplôme ou d’une certification ?,"Si oui, avez-vous obtenu le diplôme ou la certification visé(e) ?","Si non, pourquoi :",La formation a-t-elle répondu à vos attentes initiales ?,Estimez-vous que la formation était en adéquation avec le métier ou les réalités du secteur ?,Recommanderiez-vous ce stage à une personne exerçant le même métier que vous ?,Utilisez-vous les connaissances acquises lors de la formation ?,Quels étaient selon vous les principaux points forts et les principaux axes d’amélioration de cette formation ?
0,19/02/2026,ANON_76X90X48X48X57X49X50X55X55X48X53X,Formation FinOps : Maîtriser et optimiser ses ...,PLB CONSULTANT,25-FF-724-572,20/11/2025,21/11/2025,A distance,En attente,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,19/02/2026,ANON_76X90X48X48X57X49X53X52X48X56X52X,"Bâle 3, quels enjeux pour les métiers de la fi...",IFCAM,25-B3Q-739-075,20/11/2025,21/11/2025,Paris,Complétée,Oui,...,Oui,NaN,Non,NaN,NaN,"Oui, tout à fait","Oui, tout à fait","Oui, tout à fait","Oui, en partie",NaN
2,18/02/2026,ANON_76X90X48X48X57X49X50X52X49X52X56X,"Parcours nouveaux managers - Suivre, piloter e...",ERYS,25-PNM-889-284,20/11/2025,20/11/2025,Montrouge,En attente,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,18/02/2026,ANON_76X90X48X48X57X49X49X55X49X56X57X,"Parcours nouveaux managers - Suivre, piloter e...",ERYS,25-PNM-889-284,20/11/2025,20/11/2025,Montrouge,Complétée,Oui,...,Oui,ok,Non,Non,ok,"Oui, en partie","Oui, en partie","Oui, en partie","Oui, en partie",NaN
4,18/02/2026,ANON_75X88X48X48X48X48X50X55X56X55X55X,"Parcours nouveaux managers - Suivre, piloter e...",ERYS,25-PNM-889-284,20/11/2025,20/11/2025,Montrouge,En attente,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Mat compliance,Employee Code,Nom,Prénom,Genre,Type Contrat,Contrat Particulier,* Concat Contrat,Présents/non Présents,Code Régime Temps Travail,...,Code Organisation 8,Organisation 8,Date Absence,AAAA/MM Absence,Code Motif Jour Absence,Motif Jour Absence,Regroupement Jour Absences,Jour Calendaires Absence,Jours Ouvrables Absence,Jours Ouvrés Absence
0,NaN,ANON_73X74X48X49X49X57X53X51X54X51X50X,XX,XX,Masculin,CDI,NC,CDINCStandard,Présents,2,...,NC,NaN,2025-05-02,2025/05,RECUP,Récupération,Congés,1.0,1.0,1.0
1,NaN,ANON_73X74X48X49X49X57X53X51X54X51X50X,XX,XX,Masculin,CDI,NC,CDINCStandard,Présents,2,...,NC,NaN,2025-05-30,2025/05,RECUP,Récupération,Congés,1.0,1.0,1.0
2,NaN,ANON_73X74X48X49X49X57X53X51X54X51X50X,XX,XX,Masculin,CDI,NC,CDINCStandard,Présents,2,...,NC,NaN,2025-06-20,2025/06,RECUP,Récupération,Congés,1.0,1.0,1.0
3,NaN,ANON_73X74X48X49X49X57X53X51X54X51X50X,XX,XX,Masculin,CDI,NC,CDINCStandard,Présents,2,...,NC,NaN,2025-07-11,2025/07,CONGP,Congés annuels,Congés,1.0,1.0,1.0
4,NaN,ANON_73X74X48X49X49X57X53X51X54X51X50X,XX,XX,Masculin,CDI,NC,CDINCStandard,Présents,2,...,NC,NaN,2025-07-12,2025/07,CONGP,Congés annuels,Congés,1.0,1.0,0.0

In [5]:
def clean_columns(df):
    df = df.copy()
    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.lower()
        .str.replace("\n", " ", regex=False)
        .str.replace(r"\s+", "_", regex=True)
    )
    return df

df_finance = clean_columns(df_finance)
df_training = clean_columns(df_training)
df_cold = clean_columns(df_cold)
df_abs = clean_columns(df_abs)

print("Colonnes finance :", df_finance.columns.tolist())
print("Colonnes training :", df_training.columns.tolist())
print("Colonnes cold :", df_cold.columns.tolist())
print("Colonnes abs :", df_abs.columns.tolist())

Colonnes finance : ['toutes_filiales_conso', 'réel_décembre_2022', 'réel_décembre_2023', 'réel_décembre_2024', 'réel_décembre_2025', 'unnamed:_5', 'o/w_europe', 'réel_décembre_2022.1', 'réel_décembre_2023.1', 'réel_décembre_2024.1', 'réel_décembre_2025.1']
Colonnes training : ['employee_code', 'entity', 'direction', 'attended_courses', 'organization', 'seesion_start_date', 'session_end_date', 'session_id', 'status', 'total_training_hours', 'certifications', 'year']
Colonnes cold : ['date', 'matricule', 'formation', 'organization', 'session_id', 'date_de_début_de_session', 'date_de_fin_de_session', 'lieu_de_session', 'status', 'considérez-vous_que_cette_formation_vous_a_permis_de_prendre_confiance_en_vous_:', 'considérez-vous_que_cette_formation_vous_a_permis_de_faciliter_votre_quotidien_:', 'considérez-vous_que_cette_formation_vous_a_permis_d’améliorer_la_qualité_ou_l’efficacité_de_votre_travail_:', 'considérez-vous_que_cette_formation_vous_a_permis_de_vous_perfectionner_dans_un_domaine_que_vous_connaissiez_déjà_:', 'considérez-vous_que_cette_formation_vous_a_permis_de_développer_de_nouvelles_compétences_:', 'autres_(à_préciser)', 'la_formation_visait-elle_la_préparation_d’un_diplôme_ou_d’une_certification_?', 'si_oui,_avez-vous_obtenu_le_diplôme_ou_la_certification_visé(e)_?', 'si_non,_pourquoi_:', 'la_formation_a-t-elle_répondu_à_vos_attentes_initiales_?', 'estimez-vous_que_la_formation_était_en_adéquation_avec_le_métier_ou_les_réalités_du_secteur_?', 'recommanderiez-vous_ce_stage_à_une_personne_exerçant_le_même_métier_que_vous_?', 'utilisez-vous_les_connaissances_acquises_lors_de_la_formation_?', 'quels_étaient_selon_vous_les_principaux_points_forts_et_les_principaux_axes_d’amélioration_de_cette_formation_?']
Colonnes abs : ['mat_compliance', 'employee_code', 'nom', 'prénom', 'genre', 'type_contrat', 'contrat_particulier', '*_concat_contrat', 'présents/non_présents', 'code_régime_temps_travail', 'régime_temps_travail', 'régime_temps_travail+', 'code_société', 'société', 'code_niveau_6', 'niveau_6', 'code_niveau_7', 'niveau_7', 'code_niveau_8', 'niveau_8', 'code_niveau_9', 'niveau_9', 'code_organisation_1', 'organisation_1', 'code_organisation_2', 'organisation_2', 'code_organisation_3', 'organisation_3', 'code_organisation_4', 'organisation_4', 'code_organisation_5', 'organisation_5', 'code_organisation_6', 'organisation_6', 'code_organisation_7', 'organisation_7', 'code_organisation_8', 'organisation_8', 'date_absence', 'aaaa/mm_absence', 'code_motif_jour_absence', 'motif_jour_absence', 'regroupement_jour_absences', 'jour_calendaires_absence', 'jours_ouvrables_absence', 'jours_ouvrés_absence']

In [6]:
# =========================
# Préparation des dimensions de filtrage
# Objectif : conserver year / entity / direction dans toutes les tables KPI
# =========================

LEGAL_ENTITY_COL = "entity"      # entité légale dans le fichier Training
DIRECTION_COL = "direction"      # direction dans le fichier Training
ABS_ENTITY_COL = "société"       # entité légale dans le fichier Absence
ABS_DIRECTION_COL = "organisation_1"  # à ajuster si une autre colonne représente mieux la direction


def normalize_employee_code(s):
    """Normalise les matricules pour faciliter les jointures entre fichiers."""
    return s.astype(str).str.strip().str.replace(r"\.0$", "", regex=True)


def add_missing_dimension_columns(df, entity_col="entity", direction_col="direction"):
    """Garantit que les colonnes de filtre existent, même si la source ne les contient pas."""
    df = df.copy()
    if entity_col not in df.columns:
        df[entity_col] = "Non renseigné"
    if direction_col not in df.columns:
        df[direction_col] = "Non renseigné"
    df[entity_col] = df[entity_col].fillna("Non renseigné").astype(str).str.strip()
    df[direction_col] = df[direction_col].fillna("Non renseigné").astype(str).str.strip()
    return df

# Training : source principale pour entity / direction
df_training = add_missing_dimension_columns(df_training, LEGAL_ENTITY_COL, DIRECTION_COL)
df_training["employee_code"] = normalize_employee_code(df_training["employee_code"])
df_training["seesion_start_date"] = pd.to_datetime(df_training["seesion_start_date"], errors="coerce")
df_training["year"] = df_training["seesion_start_date"].dt.year

# Cold review : enrichissement entity / direction à partir du fichier Training
if "matricule" in df_cold.columns:
    df_cold["employee_code"] = normalize_employee_code(df_cold["matricule"])
else:
    df_cold["employee_code"] = np.nan

cold_date_col = "date_de_début_de_session" if "date_de_début_de_session" in df_cold.columns else "date"
df_cold[cold_date_col] = pd.to_datetime(df_cold[cold_date_col], errors="coerce")
df_cold["year"] = df_cold[cold_date_col].dt.year

training_dimensions = (
    df_training
    .sort_values("seesion_start_date")
    .drop_duplicates("employee_code", keep="last")
    [["employee_code", LEGAL_ENTITY_COL, DIRECTION_COL]]
)

df_cold = df_cold.merge(training_dimensions, on="employee_code", how="left")
df_cold = add_missing_dimension_columns(df_cold, LEGAL_ENTITY_COL, DIRECTION_COL)

# Absences : renommage pour harmoniser les dimensions
if "employee_code" in df_abs.columns:
    df_abs["employee_code"] = normalize_employee_code(df_abs["employee_code"])

df_abs["date_absence"] = pd.to_datetime(df_abs["date_absence"], errors="coerce")
df_abs["year"] = df_abs["date_absence"].dt.year

df_abs[LEGAL_ENTITY_COL] = df_abs[ABS_ENTITY_COL] if ABS_ENTITY_COL in df_abs.columns else "Non renseigné"
df_abs[DIRECTION_COL] = df_abs[ABS_DIRECTION_COL] if ABS_DIRECTION_COL in df_abs.columns else "Non renseigné"
df_abs = add_missing_dimension_columns(df_abs, LEGAL_ENTITY_COL, DIRECTION_COL)

print("Dimensions disponibles :")
print("Training:", [c for c in ["year", LEGAL_ENTITY_COL, DIRECTION_COL] if c in df_training.columns])
print("Cold review:", [c for c in ["year", LEGAL_ENTITY_COL, DIRECTION_COL] if c in df_cold.columns])
print("Absence:", [c for c in ["year", LEGAL_ENTITY_COL, DIRECTION_COL] if c in df_abs.columns])

/var/folders/yg/tr3h6f4x6rv76_r7xvqq2gb00000gq/T/ipykernel_247/767745433.py:31: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_training["seesion_start_date"] = pd.to_datetime(df_training["seesion_start_date"], errors="coerce")
/var/folders/yg/tr3h6f4x6rv76_r7xvqq2gb00000gq/T/ipykernel_247/767745433.py:41: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_cold[cold_date_col] = pd.to_datetime(df_cold[cold_date_col], errors="coerce")

Dimensions disponibles :
Training: ['year', 'entity', 'direction']
Cold review: ['year', 'entity', 'direction']
Absence: ['year', 'entity', 'direction']

In [7]:
# =========================
# Fonctions communes pour sortir les KPI selon les 3 niveaux demandés
# =========================

DIMENSIONS = {
    "yearly": ["year"],
    "by_entity": ["year", "entity"],
    "by_direction": ["year", "direction"],
}


def build_kpi_views(df, kpi_name, value_col, agg="mean", count_col=None, value_name="value"):
    """
    Renvoie 3 vues pour un KPI :
    - valeurs par année
    - répartition par entité légale
    - répartition par direction
    """
    views = {}
    for view_name, group_cols in DIMENSIONS.items():
        grouped = (
            df
            .dropna(subset=["year"])
            .groupby(group_cols, dropna=False)
            .agg(
                value=(value_col, agg),
                n=(count_col or value_col, "count")
            )
            .reset_index()
        )
        grouped.insert(0, "KPI", kpi_name)
        grouped = grouped.rename(columns={"value": value_name})
        if pd.api.types.is_numeric_dtype(grouped[value_name]):
            grouped[value_name] = grouped[value_name].round(4)
        views[view_name] = grouped
    return views


def concat_kpi_views(kpi_views_dict, view_name):
    """Concatène la même vue pour plusieurs KPI afin d'obtenir une table dashboard-friendly."""
    return pd.concat([views[view_name] for views in kpi_views_dict.values()], ignore_index=True)

In [8]:
# =========================
# KPI 1 — HCVA
# Human Capital Value Added
# =========================

pnb_row = df_finance[
    df_finance["toutes_filiales_conso"]
    .astype(str)
    .str.contains("Net Banking Income|PNB", case=False, na=False)
]

pnb_values = pnb_row[
    [
        "réel_décembre_2022",
        "réel_décembre_2023",
        "réel_décembre_2024",
        "réel_décembre_2025",
    ]
].iloc[0]

hcva_base = pd.DataFrame({
    "year": [2022, 2023, 2024, 2025],
    "pnb": pnb_values.values,
    "fte": [954.6, 926.3, 967.4, 6631.47],
})

hcva_base["HCVA"] = (hcva_base["pnb"] / hcva_base["fte"]).round(2)

# Le fichier Finance ne contient pas entity/direction au même niveau de granularité.
# On garde donc des valeurs globales filtrables via une modalité unique.
hcva_base["entity"] = "Toutes entités"
hcva_base["direction"] = "Toutes directions"

hcva_views = build_kpi_views(
    hcva_base,
    kpi_name="HCVA",
    value_col="HCVA",
    agg="mean",
    count_col="HCVA",
    value_name="HCVA"
)

hcva_views["yearly"]

    KPI  year     HCVA  n
0  HCVA  2022  1309.41  1
1  HCVA  2023  1810.79  1
2  HCVA  2024  2153.65  1
3  HCVA  2025   316.67  1

In [9]:
# =========================
# KPI 2 — KTI
# Knowledge Transfer Index
# =========================

application_col = "utilisez-vous_les_connaissances_acquises_lors_de_la_formation_?"

score_map = {
    "Oui, tout à fait": 1.0,
    "Oui, en partie": 0.5,
    "Non": 0.0,
    "Non, pas du tout": 0.0,
}

df_cold["application_score"] = df_cold[application_col].map(score_map)

kti_views = build_kpi_views(
    df_cold,
    kpi_name="KTI",
    value_col="application_score",
    agg="mean",
    count_col="application_score",
    value_name="KTI"
)

kti_views["by_entity"].head(10)

   KPI  year                      entity     KTI    n
0  KTI  2023                      CACEIS  0.7727   44
1  KTI  2023                 CACEIS Bank  0.7054  784
2  KTI  2023  CACEIS Fund Administration  0.6607  252
3  KTI  2023               Non renseigné     NaN    0
4  KTI  2024                      CACEIS  0.6757   74
5  KTI  2024                 CACEIS Bank  0.7257  720
6  KTI  2024  CACEIS Fund Administration  0.7216  264
7  KTI  2024               Non renseigné  0.8333    3
8  KTI  2025                      CACEIS  0.6286   35
9  KTI  2025                 CACEIS Bank  0.7580  498

In [10]:
# =========================
# KPI 3 — Skill Decay
# Collaborateurs sans formation depuis plus de 18 mois
# =========================

last_training = (
    df_training
    .sort_values("seesion_start_date")
    .dropna(subset=["employee_code"])
    .drop_duplicates("employee_code", keep="last")
    [["employee_code", "seesion_start_date", "year", "entity", "direction"]]
)

today = pd.Timestamp.today().normalize()
last_training["months_since_training"] = (
    (today - last_training["seesion_start_date"]).dt.days / 30.44
)
last_training["skill_decay_flag"] = last_training["months_since_training"] > 18

skill_decay_views = build_kpi_views(
    last_training,
    kpi_name="Skill Decay",
    value_col="skill_decay_flag",
    agg="mean",
    count_col="employee_code",
    value_name="pct_decay"
)

skill_decay_views["by_direction"].head(10)

           KPI    year                              direction  pct_decay   n
0  Skill Decay  2023.0                   BUSINESS DEVELOPMENT        1.0   3
1  Skill Decay  2023.0            BUT - Business Units & Tech        1.0   1
2  Skill Decay  2023.0          BUT - Custody & Cash Clearing        1.0  55
3  Skill Decay  2023.0                    BUT - Fund Services        1.0  86
4  Skill Decay  2023.0           BUT - Information Technology        1.0  18
5  Skill Decay  2023.0                 BUT - Market Solutions        1.0  10
6  Skill Decay  2023.0  CLIENT & BUSINESS DEVELOPMENT SUPPORT        1.0   4
7  Skill Decay  2023.0                             COMPLIANCE        1.0   6
8  Skill Decay  2023.0         COV - Client & Bus Dev Support        1.0   8
9  Skill Decay  2023.0                   COV - Client Success        1.0   1

In [11]:
# =========================
# KPI 4 — RE-Score
# Engagement / taux d'absentéisme
# =========================

# 1. Filtrer vraies absences, exclure les congés
has_absence_group = "regroupement_jour_absences" in df_abs.columns
if has_absence_group:
    df_abs_filtered = df_abs[
        ~df_abs["regroupement_jour_absences"]
        .astype(str)
        .str.lower()
        .str.contains("cong", na=False)
    ].copy()
else:
    df_abs_filtered = df_abs.copy()

# 2. Scores engagement fixes, à remplacer par des scores par année / entité / direction si disponibles
ier_score = 70
imr_score = 77
trust_score = 78
engagement_score = np.mean([ier_score, imr_score, trust_score])
working_days = 218


def compute_re_score(df, group_cols):
    out = (
        df
        .dropna(subset=["year"])
        .groupby(group_cols, dropna=False)
        .agg(
            total_absence_days=("jours_ouvrés_absence", "sum"),
            nb_employees=("employee_code", "nunique")
        )
        .reset_index()
    )
    out["absence_rate"] = out["total_absence_days"] / (out["nb_employees"] * working_days)
    out["engagement_score"] = engagement_score
    out["RE_score"] = out["engagement_score"] / out["absence_rate"]
    out.insert(0, "KPI", "RE-Score")
    return out.round({"absence_rate": 4, "engagement_score": 2, "RE_score": 2})

re_views = {
    view_name: compute_re_score(df_abs_filtered, group_cols)
    for view_name, group_cols in DIMENSIONS.items()
}

re_views["yearly"]

,KPI,year,total_absence_days,nb_employees,absence_rate,engagement_score,RE_score
0,RE-Score,2025,28570.0,1246,0.1052,75.0,713.06

In [12]:
# =========================
# KPI 5 — SPE
# Strategic Payroll Elasticity / part des heures stratégiques
# =========================

strategic_keywords = [
    "data", "digital", "it", "technology",
    "cyber", "security", "risk", "compliance",
    "esg", "innovation", "transformation",
]


def classify_strategic(row):
    text = (
        str(row.get("attended_courses", "")) + " " +
        str(row.get("organization", "")) + " " +
        str(row.get("direction", ""))
    ).lower()
    return "Strategic" if any(k in text for k in strategic_keywords) else "Legacy"


df_training["category"] = df_training.apply(classify_strategic, axis=1)
df_training["strategic_hours"] = np.where(
    df_training["category"] == "Strategic",
    df_training["total_training_hours"],
    0
)


def compute_spe(df, group_cols):
    out = (
        df
        .dropna(subset=["year"])
        .groupby(group_cols, dropna=False)
        .agg(
            strategic_hours=("strategic_hours", "sum"),
            total_hours=("total_training_hours", "sum"),
            nb_formations=("employee_code", "count")
        )
        .reset_index()
    )
    out["strategic_share"] = out["strategic_hours"] / out["total_hours"]
    out.insert(0, "KPI", "SPE Strategic Share")
    return out.round({"strategic_share": 4})

spe_views = {
    view_name: compute_spe(df_training, group_cols)
    for view_name, group_cols in DIMENSIONS.items()
}

spe_views["by_entity"].head(10)

,KPI,year,entity,strategic_hours,total_hours,nb_formations,strategic_share
0,SPE Strategic Share,2022.0,CACEIS Bank,20.00,20.05,2,0.9975
1,SPE Strategic Share,2022.0,CACEIS Sa,0.00,14.00,1,0.0000
2,SPE Strategic Share,2023.0,CACEIS,945.70,2919.66,331,0.3239
3,SPE Strategic Share,2023.0,CACEIS Bank,12434.85,29592.28,4241,0.4202
4,SPE Strategic Share,2023.0,CACEIS Fund Administration,2943.54,10163.40,1279,0.2896
5,SPE Strategic Share,2023.0,CACEIS Sa,0.50,7.70,8,0.0649
6,SPE Strategic Share,2024.0,CACEIS,381.98,2290.60,280,0.1668
7,SPE Strategic Share,2024.0,CACEIS Bank,11191.10,28225.44,3294,0.3965
8,SPE Strategic Share,2024.0,CACEIS Fund Administration,1735.54,7447.76,935,0.2330
9,SPE Strategic Share,2024.0,CACEIS Sa,0.00,0.01,4,0.0000

In [13]:
# =========================
# Tables finales pour dashboard / export
# =========================

all_kpi_views = {
    "HCVA": hcva_views,
    "KTI": kti_views,
    "Skill Decay": skill_decay_views,
}

kpi_yearly = pd.concat(
    [
        hcva_views["yearly"],
        kti_views["yearly"],
        skill_decay_views["yearly"],
        re_views["yearly"],
        spe_views["yearly"],
    ],
    ignore_index=True,
    sort=False,
)

kpi_by_entity = pd.concat(
    [
        hcva_views["by_entity"],
        kti_views["by_entity"],
        skill_decay_views["by_entity"],
        re_views["by_entity"],
        spe_views["by_entity"],
    ],
    ignore_index=True,
    sort=False,
)

kpi_by_direction = pd.concat(
    [
        hcva_views["by_direction"],
        kti_views["by_direction"],
        skill_decay_views["by_direction"],
        re_views["by_direction"],
        spe_views["by_direction"],
    ],
    ignore_index=True,
    sort=False,
)

print("kpi_yearly", kpi_yearly.shape)
print("kpi_by_entity", kpi_by_entity.shape)
print("kpi_by_direction", kpi_by_direction.shape)

display(kpi_yearly.head(20))
display(kpi_by_entity.head(20))
display(kpi_by_direction.head(20))

kpi_yearly (16, 15)
kpi_by_entity (46, 16)
kpi_by_direction (302, 16)

,KPI,year,HCVA,n,KTI,pct_decay,total_absence_days,nb_employees,absence_rate,engagement_score,RE_score,strategic_hours,total_hours,nb_formations,strategic_share
0,HCVA,2022.0,1309.41,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HCVA,2023.0,1810.79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HCVA,2024.0,2153.65,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HCVA,2025.0,316.67,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,KTI,2023.0,NaN,1080.0,0.6977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,KTI,2024.0,NaN,1061.0,0.7215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,KTI,2025.0,NaN,649.0,0.7419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Skill Decay,2023.0,NaN,292.0,NaN,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Skill Decay,2024.0,NaN,522.0,NaN,0.6992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Skill Decay,2025.0,NaN,1324.0,NaN,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,RE-Score,2025.0,NaN,NaN,NaN,NaN,28570.0,1246.0,0.1052,75.0,713.06,NaN,NaN,NaN,NaN
11,SPE Strategic Share,2022.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.00,34.05,3.0,0.5874
12,SPE Strategic Share,2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16324.59,42683.04,5859.0,0.3825
13,SPE Strategic Share,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13324.12,38029.81,4525.0,0.3504
14,SPE Strategic Share,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15339.19,37322.71,4100.0,0.4110
15,SPE Strategic Share,2026.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,3.50,2.0,0.0000

,KPI,year,entity,HCVA,n,KTI,pct_decay,total_absence_days,nb_employees,absence_rate,engagement_score,RE_score,strategic_hours,total_hours,nb_formations,strategic_share
0,HCVA,2022.0,Toutes entités,1309.41,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HCVA,2023.0,Toutes entités,1810.79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HCVA,2024.0,Toutes entités,2153.65,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HCVA,2025.0,Toutes entités,316.67,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,KTI,2023.0,CACEIS,NaN,44.0,0.7727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,KTI,2023.0,CACEIS Bank,NaN,784.0,0.7054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,KTI,2023.0,CACEIS Fund Administration,NaN,252.0,0.6607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,KTI,2023.0,Non renseigné,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,KTI,2024.0,CACEIS,NaN,74.0,0.6757,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,KTI,2024.0,CACEIS Bank,NaN,720.0,0.7257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,KTI,2024.0,CACEIS Fund Administration,NaN,264.0,0.7216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,KTI,2024.0,Non renseigné,NaN,3.0,0.8333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,KTI,2025.0,CACEIS,NaN,35.0,0.6286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,KTI,2025.0,CACEIS Bank,NaN,498.0,0.7580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,KTI,2025.0,CACEIS Fund Administration,NaN,112.0,0.7054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,KTI,2025.0,Non renseigné,NaN,4.0,0.7500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Skill Decay,2023.0,CACEIS,NaN,18.0,NaN,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Skill Decay,2023.0,CACEIS Bank,NaN,176.0,NaN,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Skill Decay,2023.0,CACEIS Fund Administration,NaN,98.0,NaN,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Skill Decay,2024.0,CACEIS,NaN,24.0,NaN,0.7083,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,KPI,year,direction,HCVA,n,KTI,pct_decay,total_absence_days,nb_employees,absence_rate,engagement_score,RE_score,strategic_hours,total_hours,nb_formations,strategic_share
0,HCVA,2022.0,Toutes directions,1309.41,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HCVA,2023.0,Toutes directions,1810.79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HCVA,2024.0,Toutes directions,2153.65,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HCVA,2025.0,Toutes directions,316.67,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,KTI,2023.0,BUSINESS DEVELOPMENT,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,KTI,2023.0,BUT - Business Units & Tech,NaN,1.0,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,KTI,2023.0,BUT - Custody & Cash Clearing,NaN,136.0,0.6912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,KTI,2023.0,BUT - Fund Services,NaN,265.0,0.6698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,KTI,2023.0,BUT - Gen Secretary & Controls,NaN,17.0,0.7059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,KTI,2023.0,BUT - Inf System Sec & Resil,NaN,20.0,0.7250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,KTI,2023.0,BUT - Information Technology,NaN,75.0,0.7267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,KTI,2023.0,BUT - Market Solutions,NaN,40.0,0.6750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,KTI,2023.0,CLIENT & BUSINESS DEVELOPMENT SUPPORT,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,KTI,2023.0,COMPLIANCE,NaN,1.0,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,KTI,2023.0,COV - Client & Bus Dev Support,NaN,69.0,0.6232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,KTI,2023.0,COV - Client Success,NaN,27.0,0.6852,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,KTI,2023.0,COV - Coverage France,NaN,15.0,0.8667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,KTI,2023.0,COV - General Secretary,NaN,15.0,0.6000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,KTI,2023.0,COV - PERES,NaN,95.0,0.7158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,KTI,2023.0,DEPOSITARY CONTROL,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Optionnel : export des tables finales
output_dir = Path("outputs")
output_dir.mkdir(exist_ok=True)

kpi_yearly.to_csv(output_dir / "kpi_yearly.csv", index=False)
kpi_by_entity.to_csv(output_dir / "kpi_by_entity.csv", index=False)
kpi_by_direction.to_csv(output_dir / "kpi_by_direction.csv", index=False)

print("Exports créés dans", output_dir.resolve())

Exports créés dans /Users/CoursM2/Documents/Alberthon/outputs

### Résultat attendu

Le préprocessing conserve maintenant les dimensions nécessaires au filtrage :

- `year` pour suivre chaque KPI dans le temps ;
- `entity` pour filtrer / répartir par entité légale ;
- `direction` pour filtrer / répartir par direction.

Les trois tables finales à utiliser dans un dashboard sont :

- `kpi_yearly` : valeurs par année ;
- `kpi_by_entity` : valeurs par année et entité légale ;
- `kpi_by_direction` : valeurs par année et direction.

À noter : le fichier Finance utilisé pour le HCVA ne contient pas de granularité `entity` / `direction` exploitable dans ce notebook. Le HCVA est donc conservé en global avec les modalités `Toutes entités` et `Toutes directions`. Pour obtenir un vrai HCVA par entité ou direction, il faut une source Finance/FTE au même niveau de granularité.